version: "3.8"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/home/oryndoon/data/site:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "~/home/oryndoon/data/site:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    env_file: .env

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/home/oryndoon/data/mariadb:/var/lib/mysql"
    networks:
      - backend
    restart: always
    env_file: .env

networks:
  frontend:
  backend:
