version: "3.8"
services:
  nginx:
    build: requirements/nginx/
    container_name: "nginx_container"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/home/oryndoon/data/website:/var/www/html"
    networks:
      - inception-net
    restart: always

  mariadb:
    build: requirements/mariadb
    container_name: "mariadb_container"
    ports:
      - "3306:3306"
    volumes:
      - "~/home/oryndoon/data/mariadb:/var/lib/mysql"
    networks:
      - inception-net
    env_file: .env
    restart: always

networks:
  inception-net: