version: "3.8"
services:
  nginx:
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    restart: always

  mariadb:
    build: requirements/mariadb
    ports:
      - "1001:1001"
    networks:
      - backend
    restart: always